kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assisted-service
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - nodes
      - pods
      - endpoints
      - services
      - secrets
  - verbs:
      - get
      - watch
      - list
      - create
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - watch
      - list
      - delete
      - create
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - list
    apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
  - verbs:
      - create
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
