kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assisted-service
  namespace: default
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - endpoints
      - services
  - verbs:
      - get
      - watch
      - list
      - delete
      - create
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames: ["assisted-service-leader-election-helper", "assisted-service-migration-helper", "assisted-service-baseiso-helper"]
