kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assisted-service
  namespace: default
rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
      - create

  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - update
      - delete
    resourceNames:
      - assisted-service-baseiso-helper
      - assisted-service-leader-election-helper
      - assisted-service-migration-helper

  - apiGroups:
    - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - delete
