version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - copyloopvar
    - gocyclo
    - gosec
    - unconvert
  settings:
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - Infof
            - Warnf
            - Errorf
            - Fatalf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: G107
      - path: (.+)\.go$
        text: G402
      - path: (.+)\.go$
        text: G108
    paths:
      - build
      - client
      - docs
      - models
      - restapi
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - build
      - client
      - docs
      - models
      - restapi
      - third_party$
      - builtin$
      - examples$
