FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
RUN mkdir /root/image
# You can get RHCOS releases from here https://releases-rhcos.cloud.privileged.psi.redhat.com/
RUN curl -L -k https://releases-rhcos.cloud.privileged.psi.redhat.com/storage/releases/4.6-devel/46.82.202008181531-0/x86_64/rhcos-46.82.202008181531-0-live.x86_64.iso -o /root/image/livecd.iso
