FROM quay.io/ocpmetal/assisted-service:latest AS assisted-service
FROM quay.io/ocpmetal/assisted-iso-create:latest AS assisted-iso-create

FROM quay.io/app-sre/centos:8

ARG WORK_DIR=/data
ARG USER=assisted-installer
ARG NAMESPACE=assisted-installer
# downstream this can be installed as an RPM
ARG OC_URL=https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz

# openshift-install requires this
RUN dnf install -y libvirt-libs && yum clean all

RUN mkdir $WORK_DIR && chmod 755 $WORK_DIR
RUN useradd $USER
RUN chown $USER:$USER $WORK_DIR

# ISO
ARG RHCOS_VERSION
COPY --from=assisted-iso-create $WORK_DIR/coreos-installer $WORK_DIR
COPY --from=assisted-iso-create $WORK_DIR/livecd.iso $WORK_DIR/livecd-$RHCOS_VERSION.iso
COPY --from=assisted-iso-create $WORK_DIR/assisted-iso-create $WORK_DIR
ENV COREOS_IMAGE=$WORK_DIR/livecd.iso

# install oc binary
RUN curl -s $OC_URL | tar -xzC /usr/local/bin/ oc

ENV WORK_DIR=$WORK_DIR

COPY --from=assisted-service /assisted-service /assisted-service
CMD ["/assisted-service"]
