FROM        registry.ci.openshift.org/openshift/release:golang-1.16

ENV         GO111MODULE=on
ENV         GOFLAGS=""

WORKDIR     /assisted-service

RUN         curl -sSfL \
https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
sh -s -- -b $(go env GOPATH)/bin v1.24.0

RUN         go get \
github.com/onsi/ginkgo/ginkgo@v1.12.2 \
golang.org/x/tools/cmd/goimports@v0.0.0-20200616195046-dc31b401abb5 \
github.com/golang/mock/mockgen@v1.4.3 \
github.com/vektra/mockery/.../@v1.1.2

COPY        . ./

ENTRYPOINT  ["make"]
CMD         ["build-minimal"]
