# Generate python client
FROM quay.io/ocpmetal/swagger-codegen-cli:2.4.15 as swagger_py

COPY swagger.yaml .
COPY tools/generate_python_client.sh .
RUN chmod +x ./generate_python_client.sh && SWAGGER_FILE=swagger.yaml OUTPUT=/build ./generate_python_client.sh

# Build binaries
FROM registry.svc.ci.openshift.org/openshift/release:golang-1.15 as builder
COPY . .
COPY --from=swagger_py /build build
RUN cd build && python3 setup.py sdist --dist-dir /assisted-service-client

# Create final image
FROM quay.io/centos/centos:centos8

# openshift-install requires this
RUN yum install -y libvirt-libs && yum clean all

ARG WORK_DIR=/data

RUN mkdir $WORK_DIR && chmod 775 $WORK_DIR

# downstream this can be installed as an RPM
ARG OC_URL=https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
RUN curl -s $OC_URL | tar -xzC /usr/local/bin/ oc

COPY --from=builder /assisted-service-client/assisted-service-client-*.tar.gz /clients/