FROM registry.access.redhat.com/ubi9/go-toolset:1.25 AS golang

RUN GOFLAGS=-mod=mod go install github.com/go-delve/delve/cmd/dlv@v1.21.2

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:3816d303e75dec4da2d10eeb9e8651eef4393721598bea4690c607282635aa57 AS builder

# Exclude i686 packages to avoid glibc-devel multilib dependency issues in UBI9
RUN dnf install -y --setopt=multilib_policy=best --exclude='*.i686' gcc git nmstate-devel openssl-devel make && \
    dnf clean all

ENV GOROOT=/usr/lib/golang
ENV GOPATH=/opt/app-root/src/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
# For build-minimal target
ENV DEBUG_SERVICE=true

COPY --from=golang $GOPATH $GOPATH
COPY --from=golang $GOROOT $GOROOT

RUN chmod 775 -R $GOPATH && chmod 775 -R $GOROOT

RUN git config --global --add safe.directory /opt/app-root/src
COPY . ./assisted-service
RUN cd ./assisted-service && make build-minimal

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71

RUN microdnf install -y nmstate nmstate-libs && microdnf clean all

ARG DEBUG_SERVICE_PORT=40000
EXPOSE 8090 $DEBUG_SERVICE_PORT

COPY --from=builder /opt/app-root/src/go/bin/dlv /usr/bin/dlv
COPY --from=builder /assisted-service/build/assisted-installer/assisted-service /assisted-service
COPY --from=builder /assisted-service/build/assisted-installer/assisted-service-operator /assisted-service-operator

CMD ["dlv", "--listen=:40000", "--headless=true", "--continue", "--api-version=2", "--accept-multiclient", "exec", "/assisted-service"]
