# ISO
FROM quay.io/coreos/coreos-installer:release AS coreos-installer
FROM quay.io/ocpmetal/livecd-iso:rhcos-livecd AS livecd

# install config
# [TODO] - remove this line, once we are ready to use openshift-installer from the release
FROM quay.io/ocpmetal/openshift-installer  AS openshift-installer
#[TODO] - change ignition-manifests-and-kubeconfig-generate to assisted-installer-generator once a stable was created
FROM quay.io/ocpmetal/assisted-ignition-generator:stable as config-gen

FROM fedora:31

ARG GIT_REVISION
ARG WORK_DIR=/data
ARG USER=assisted-installer

LABEL "git_revision"=${GIT_REVISION}

RUN dnf install -y python pip libvirt-devel && dnf clean all && pip install boto3 botocore

RUN mkdir $WORK_DIR && chmod 755 $WORK_DIR
RUN useradd $USER
RUN chown $USER:$USER $WORK_DIR

# ISO
COPY --from=coreos-installer /usr/sbin/coreos-installer $WORK_DIR
COPY --from=livecd /root/image/livecd.iso $WORK_DIR/livecd.iso
COPY build/assisted-iso-create $WORK_DIR
ENV COREOS_IMAGE=$WORK_DIR/livecd.iso

# install config
# [TODO] - change this line to use openshift-installer from the release, once we are ready
COPY --from=openshift-installer /root/installer/openshift-install $WORK_DIR
COPY --from=config-gen $WORK_DIR/process-ignition-manifests-and-kubeconfig.py $WORK_DIR

ENV WORK_DIR=$WORK_DIR

ADD build/assisted-service /assisted-service
CMD ["/assisted-service"]
