repo_url: https://github.com/openshift/assisted-service
site_name: 'Openshift Assisted Service'
site_description: 'Helper Assistant to deploy and manage your OCP Clusters'
site_author: Openshift Assisted Service Team
theme: readthedocs
edit_uri: ""
nav:
    - OAS Home: 'index.md'
    - OAS Deployment:
        - OAS Running on Local: 'user-guide/assisted-service-on-local.md'
        - OAS Running on Openshift: 'user-guide/assisted-service-on-openshift.md'
    - Openshift Deployment: 
        - User Guide Index: 'user-guide/user-guide.md'
        - OCP Deployment on Local: 'user-guide/deploy-on-local.md'
        - OCP Deployment on Bare Metal: 'user-guide/deploy-on-bare-metal.md'
        - OCP Deployment on vSphere: 'user-guide/deploy-on-vsphere.md'
        - OCP Deployment on RHEV: 'user-guide/deploy-on-RHEV.md'
        - OCP Deployment on Openstack: 'user-guide/deploy-on-OSP.md'
    - OAS Development:
        - Migrations: 'dev/migrations.md'
