kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assisted-service
  namespace: default
subjects:
  - kind: ServiceAccount
    name: assisted-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assisted-service
