#!/usr/bin/env bash
export CATALOG_SOURCE_NAME="${CATALOG_SOURCE_NAME:-community-operators}"
export CHANNEL="${CHANNEL_INSTALL_OVERRIDE:-ocm-2.3}"
export ASSISTED_UPGRADE_OPERATOR="${ASSISTED_UPGRADE_OPERATOR:-true}"
export ASSISTED_STOP_AFTER_AGENT_DISCOVERY="${ASSISTED_STOP_AFTER_AGENT_DISCOVERY:-false}"
