---
apiVersion: v1
kind: Service
metadata:
  name: assisted-service-nodeport
  namespace: assisted-installer
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30000
      port: 8090
  selector:
    app: assisted-service
