apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-list
  namespace: assisted-installer
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: s3-list
            image: amazon/aws-cli
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_secret_access_key
            command: ["aws"]
            args: ["--endpoint-url", "http://cloudserver-front:8000", "s3api", "list-objects", "--bucket", "test"]
          restartPolicy: OnFailure
      backoffLimit: 3
