// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-service/pkg/ocm (interfaces: OCMAccountsMgmt)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package ocm -destination mock_accounts_mgmt.go . OCMAccountsMgmt
//

// Package ocm is a generated GoMock package.
package ocm

import (
	context "context"
	reflect "reflect"

	strfmt "github.com/go-openapi/strfmt"
	v1 "github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockOCMAccountsMgmt is a mock of OCMAccountsMgmt interface.
type MockOCMAccountsMgmt struct {
	ctrl     *gomock.Controller
	recorder *MockOCMAccountsMgmtMockRecorder
	isgomock struct{}
}

// MockOCMAccountsMgmtMockRecorder is the mock recorder for MockOCMAccountsMgmt.
type MockOCMAccountsMgmtMockRecorder struct {
	mock *MockOCMAccountsMgmt
}

// NewMockOCMAccountsMgmt creates a new mock instance.
func NewMockOCMAccountsMgmt(ctrl *gomock.Controller) *MockOCMAccountsMgmt {
	mock := &MockOCMAccountsMgmt{ctrl: ctrl}
	mock.recorder = &MockOCMAccountsMgmtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCMAccountsMgmt) EXPECT() *MockOCMAccountsMgmtMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockOCMAccountsMgmt) CreateSubscription(ctx context.Context, clusterID strfmt.UUID, clusterName string) (*v1.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, clusterID, clusterName)
	ret0, _ := ret[0].(*v1.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockOCMAccountsMgmtMockRecorder) CreateSubscription(ctx, clusterID, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).CreateSubscription), ctx, clusterID, clusterName)
}

// DeleteSubscription mocks base method.
func (m *MockOCMAccountsMgmt) DeleteSubscription(ctx context.Context, subscriptionID strfmt.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockOCMAccountsMgmtMockRecorder) DeleteSubscription(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).DeleteSubscription), ctx, subscriptionID)
}

// GetSubscription mocks base method.
func (m *MockOCMAccountsMgmt) GetSubscription(ctx context.Context, subscriptionID strfmt.UUID) (*v1.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, subscriptionID)
	ret0, _ := ret[0].(*v1.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockOCMAccountsMgmtMockRecorder) GetSubscription(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).GetSubscription), ctx, subscriptionID)
}

// UpdateSubscriptionConsoleUrl mocks base method.
func (m *MockOCMAccountsMgmt) UpdateSubscriptionConsoleUrl(ctx context.Context, subscriptionID strfmt.UUID, consoleUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionConsoleUrl", ctx, subscriptionID, consoleUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionConsoleUrl indicates an expected call of UpdateSubscriptionConsoleUrl.
func (mr *MockOCMAccountsMgmtMockRecorder) UpdateSubscriptionConsoleUrl(ctx, subscriptionID, consoleUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionConsoleUrl", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).UpdateSubscriptionConsoleUrl), ctx, subscriptionID, consoleUrl)
}

// UpdateSubscriptionDisplayName mocks base method.
func (m *MockOCMAccountsMgmt) UpdateSubscriptionDisplayName(ctx context.Context, subscriptionID strfmt.UUID, displayName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionDisplayName", ctx, subscriptionID, displayName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionDisplayName indicates an expected call of UpdateSubscriptionDisplayName.
func (mr *MockOCMAccountsMgmtMockRecorder) UpdateSubscriptionDisplayName(ctx, subscriptionID, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionDisplayName", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).UpdateSubscriptionDisplayName), ctx, subscriptionID, displayName)
}

// UpdateSubscriptionOpenshiftClusterID mocks base method.
func (m *MockOCMAccountsMgmt) UpdateSubscriptionOpenshiftClusterID(ctx context.Context, subscriptionID, openshiftClusterID strfmt.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionOpenshiftClusterID", ctx, subscriptionID, openshiftClusterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionOpenshiftClusterID indicates an expected call of UpdateSubscriptionOpenshiftClusterID.
func (mr *MockOCMAccountsMgmtMockRecorder) UpdateSubscriptionOpenshiftClusterID(ctx, subscriptionID, openshiftClusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionOpenshiftClusterID", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).UpdateSubscriptionOpenshiftClusterID), ctx, subscriptionID, openshiftClusterID)
}

// UpdateSubscriptionStatusActive mocks base method.
func (m *MockOCMAccountsMgmt) UpdateSubscriptionStatusActive(ctx context.Context, subscriptionID strfmt.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionStatusActive", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionStatusActive indicates an expected call of UpdateSubscriptionStatusActive.
func (mr *MockOCMAccountsMgmtMockRecorder) UpdateSubscriptionStatusActive(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionStatusActive", reflect.TypeOf((*MockOCMAccountsMgmt)(nil).UpdateSubscriptionStatusActive), ctx, subscriptionID)
}
