FROM base

COPY --from=quay.io/openshift/origin-cli:latest /usr/bin/oc /usr/bin/kubectl /usr/bin/
COPY --from=registry.k8s.io/kustomize/kustomize:v4.5.7 /app/kustomize /usr/bin/

RUN dnf install -y openssl

RUN make build-openshift-ci-test-bin
RUN go mod vendor
