// Code generated by go-swagger; DO NOT EDIT.

package managed_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListManagedDomainsParams creates a new ListManagedDomainsParams object
// no default values defined in spec.
func NewListManagedDomainsParams() ListManagedDomainsParams {

	return ListManagedDomainsParams{}
}

// ListManagedDomainsParams contains all the bound params for the list managed domains operation
// typically these are obtained from a http.Request
//
// swagger:parameters ListManagedDomains
type ListManagedDomainsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListManagedDomainsParams() beforehand.
func (o *ListManagedDomainsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
