# permissions for end users to view assistedservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assistedservice-viewer-role
rules:
- apiGroups:
  - assistedservice.openshift.io.openshift.io
  resources:
  - assistedservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - assistedservice.openshift.io.openshift.io
  resources:
  - assistedservices/status
  verbs:
  - get
