
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - adi.io.my.domain
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adi.io.my.domain
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - adi.io.my.domain
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adi.io.my.domain
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - adi.io.my.domain
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adi.io.my.domain
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments/status
  verbs:
  - get
  - patch
  - update
