resources:
- ./ocp
- leader_election_role.yaml
- leader_election_role_binding.yaml
- role.yaml
- role_binding.yaml
# Adding the service account causes it to be included
# in the bundle manifests which we don't want
#- service_account.yaml
# Done via kube_api_roles
#- role_binding.yaml
#- leader_election_role.yaml
#- leader_election_role_binding.yaml
