// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GenerateClusterISOReader is a Reader for the GenerateClusterISO structure.
type GenerateClusterISOReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateClusterISOReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGenerateClusterISOCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGenerateClusterISOBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGenerateClusterISONotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGenerateClusterISOInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGenerateClusterISOCreated creates a GenerateClusterISOCreated with default headers values
func NewGenerateClusterISOCreated() *GenerateClusterISOCreated {
	return &GenerateClusterISOCreated{}
}

/*GenerateClusterISOCreated handles this case with default header values.

Created ISO
*/
type GenerateClusterISOCreated struct {
	Payload *GenerateClusterISOCreatedBody
}

func (o *GenerateClusterISOCreated) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOCreated  %+v", 201, o.Payload)
}

func (o *GenerateClusterISOCreated) GetPayload() *GenerateClusterISOCreatedBody {
	return o.Payload
}

func (o *GenerateClusterISOCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GenerateClusterISOCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateClusterISOBadRequest creates a GenerateClusterISOBadRequest with default headers values
func NewGenerateClusterISOBadRequest() *GenerateClusterISOBadRequest {
	return &GenerateClusterISOBadRequest{}
}

/*GenerateClusterISOBadRequest handles this case with default header values.

Invalid input
*/
type GenerateClusterISOBadRequest struct {
}

func (o *GenerateClusterISOBadRequest) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOBadRequest ", 400)
}

func (o *GenerateClusterISOBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISONotFound creates a GenerateClusterISONotFound with default headers values
func NewGenerateClusterISONotFound() *GenerateClusterISONotFound {
	return &GenerateClusterISONotFound{}
}

/*GenerateClusterISONotFound handles this case with default header values.

Cluster not found
*/
type GenerateClusterISONotFound struct {
}

func (o *GenerateClusterISONotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISONotFound ", 404)
}

func (o *GenerateClusterISONotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateClusterISOInternalServerError creates a GenerateClusterISOInternalServerError with default headers values
func NewGenerateClusterISOInternalServerError() *GenerateClusterISOInternalServerError {
	return &GenerateClusterISOInternalServerError{}
}

/*GenerateClusterISOInternalServerError handles this case with default header values.

Internal server error
*/
type GenerateClusterISOInternalServerError struct {
}

func (o *GenerateClusterISOInternalServerError) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/downloads/image][%d] generateClusterISOInternalServerError ", 500)
}

func (o *GenerateClusterISOInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GenerateClusterISOCreatedBody generate cluster i s o created body
swagger:model GenerateClusterISOCreatedBody
*/
type GenerateClusterISOCreatedBody struct {

	// image Id
	// Format: uuid
	ImageID strfmt.UUID `json:"imageId,omitempty"`
}

// Validate validates this generate cluster i s o created body
func (o *GenerateClusterISOCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateImageID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GenerateClusterISOCreatedBody) validateImageID(formats strfmt.Registry) error {

	if swag.IsZero(o.ImageID) { // not required
		return nil
	}

	if err := validate.FormatOf("generateClusterISOCreated"+"."+"imageId", "body", "uuid", o.ImageID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GenerateClusterISOCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GenerateClusterISOCreatedBody) UnmarshalBinary(b []byte) error {
	var res GenerateClusterISOCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
