apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  namespace: kube-amd-gpu
  name: default
spec:
  devicePlugin:
    devicePluginImage: docker.io/rocm/k8s-device-plugin:latest
    nodeLabellerImage: docker.io/rocm/k8s-device-plugin:labeller-latest
  driver:
    version: 6.2.2
  selector:
    feature.node.kubernetes.io/amd-gpu: 'true'