{
 "title": "Status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "CPU Seconds Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Go Threads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "targets": [
    { "expr": "go_threads" }
   ]
  }
 ]
}