apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: amd-vnic
  namespace: {{ .Operator.Namespace }}
spec:
  rules:
  - name: amd-vnic
    labels:
      feature.node.kubernetes.io/amd-vnic: "true"
    matchFeatures:
    - feature: pci.device
      matchExpressions:
        vendor: {op: In, value: ["1dd8"]} # AMD Pensando
        device:
          op: In
          value:
          - "1003" # DSC Ethernet Controller (VF)
        subsystem_vendor: {op: In, value: ["1dd8"]}
        subsystem_device:
          op: In
          value:
          - "5201" # Pollara-1Q400
