apiVersion: v1
kind: Secret
metadata:
  name: assisted-installer-sso
  namespace: "assisted-installer"
  labels:
    app: assisted-service
type: Opaque
stringData:
  ocm-service.clientId: ""
  ocm-service.clientSecret: ""
