kind: Service
apiVersion: v1
metadata:
  name: ocp-metal-ui
  namespace: "assisted-installer"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      # nodePort: 31000
  selector:
    app: ocp-metal-ui
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ocp-metal-ui
  namespace: "assisted-installer"
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name _;

      root /app;
      index index.html;

      location /api {
          proxy_pass http://assisted-service.assisted-installer.svc.cluster.local:8090;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_connect_timeout 120;
          proxy_send_timeout 120;
          proxy_read_timeout 120;
          send_timeout 120;
      }

      location / {
         try_files $uri /index.html;
      }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocp-metal-ui
  namespace: "assisted-installer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-metal-ui
  template:
    metadata:
      labels:
        app: ocp-metal-ui
    spec:
      containers:
        - name: ocp-metal-ui
          image: quay.io/ocpmetal/ocp-metal-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/bitnami/nginx/conf/server_blocks/
              readOnly: true
              name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: ocp-metal-ui
            items:
              - key: nginx.conf
                path: default.conf
      restartPolicy: Always
