apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: db.name
              name: assisted-installer-rds
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: db.user
              name: assisted-installer-rds
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: assisted-installer-rds
        image: quay.io/ocpmetal/postgresql-12-centos7
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: assisted-installer
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: LoadBalancer
status:
  loadBalancer: {}
