apiVersion: apps/v1
kind: Deployment
metadata:
  name: scality
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality
  template:
    metadata:
      labels:
        app: scality
    spec:
      containers:
      - env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: assisted-installer-s3
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: assisted-installer-s3
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: aws_region
              name: assisted-installer-s3
        - name: BUCKET
          valueFrom:
            secretKeyRef:
              key: bucket
              name: assisted-installer-s3
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: assisted-installer-s3
        - name: S3DATAPATH
          valueFrom:
            secretKeyRef:
              key: s3_data_path
              name: assisted-installer-s3
        - name: S3METADATAPATH
          valueFrom:
            secretKeyRef:
              key: s3_metadata_path
              name: assisted-installer-s3
        image: quay.io/ocpmetal/s3server
        imagePullPolicy: Always
        name: s3server
        resources:
          limits:
            cpu: 500m
            memory: 2000Mi
          requests:
            cpu: 300m
            memory: 2000Mi
        volumeMounts:
        - mountPath: /mnt/data
          name: scalityvol
      volumes:
      - name: scalityvol
        persistentVolumeClaim:
          claimName: scality-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  name: cloudserver-front
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: scality
status:
  loadBalancer: {}