apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-agent-cluster-install
  namespace: spoke-cluster
spec:
  clusterDeploymentRef:
    name: single-node
  imageSetRef:
    name: openshift-v4.8.0
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineNetwork:
    - cidr: 192.168.126.0/24
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 1
 #sshPublicKey: ssh-rsa your-public-key-here (optional)