MAIN_README="${SCRIPT_DIR}"/README.md
echo '# State machines' > "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo 'This directory contains documentation for the state machines for the assisted installer.' >> "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo '## Host state machine' >> "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo 'You can find documentation for the host state machine [here](./doc/host_state_machine).' >> "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo '## Cluster state machine' >> "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo 'You can find documentation for the cluster state machine [here](./doc/cluster_state_machine).' >> "${MAIN_README}"
echo '## Unbound host state machine' >> "${MAIN_README}"
echo '' >> "${MAIN_README}"
echo 'You can find documentation for the unbound host state machine [here](./doc/unbound_host_state_machine).' >> "${MAIN_README}"
