apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: object-store
  name: object-store
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-store
  template:
    metadata:
      labels:
        app: object-store
    spec:
      containers:
        - image: quay.io/flysangel/chrislusf/seaweedfs@sha256:a27e9c432f1dfaafb5bb3f5b39065c0df7a15423a3894025c714b3f06f998aeb
          name: s3server
          args:
            - mini
            - -dir=/data
            - -s3.port=9000
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_secret_access_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_access_key_id
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 2000Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: object-store
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-store
  name: object-store
  namespace: REPLACE_NAMESPACE
spec:
  ports:
    - name: object-store
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: object-store
  type: LoadBalancer
status:
  loadBalancer: {}
