apiVersion: v1
kind: Secret
metadata:
  name: assisted-installer-public-s3
  namespace: REPLACE_NAMESPACE
  labels:
    app: object-store
type: Opaque
stringData:
  aws_access_key_id: "accessKey1"
  aws_region: "us-east-1"
  aws_secret_access_key: "verySecretKey1"
  bucket: "pub-test"
  endpoint: "http://object-store:9000"
