apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: assisted-service-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: assisted-service-manager-role
subjects:
- kind: ServiceAccount
  name: assisted-service
  namespace: default
