apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Operator.Namespace }}-setup
subjects:
- kind: ServiceAccount
  namespace: {{ .Operator.Namespace }}
  name: setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Operator.Namespace }}-setup