apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: {{ .Operator.Namespace }}
  name: {{ .Operator.SubscriptionName }}
spec:
  name: kernel-module-management
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable
  installPlanApproval: Automatic