{
 "title": "Assisted Service Resurce Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total {namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m]))/ sum(kube_pod_container_resource_limits_cpu_cores {namespace=\"$namespace\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[5m])) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods Network Received ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods Network Transmited ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total {namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"assisted-service-.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  }
 ]
}