{
 "title": "Elasticsearch",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(domain_name)" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(aws_es_cluster_status_green_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "green"
    },
    {
     "expr": "max(aws_es_cluster_status_yellow_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(aws_es_cluster_status_red_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_es_nodes_maximum{domain_name=\"${cluster}\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Searchable documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_es_searchable_documents_maximum{domain_name=\"${cluster}\"}) by (domain_name)"
    }
   ]
  },
  {
   "title": "Index Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(aws_es_indexing_latency_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Indexing Latency"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(aws_es_search_latency_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Indexing Latency"
    }
   ]
  },
  {
   "title": "Memory and CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(aws_es_jvmmemory_pressure_maximum{domain_name=\"${cluster}\"}) by (host)",
       "legendFormat": "max"
      },
      {
       "expr": "min(aws_es_jvmmemory_pressure_maximum{domain_name=\"${cluster}\"}) by (host)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(aws_es_jvmmemory_pressure_maximum{domain_name=\"${cluster}\"}) by (host)",
       "legendFormat": "avg"
      },
      {
       "expr": "stddev(aws_es_jvmmemory_pressure_maximum{domain_name=\"${cluster}\"}) by (host)",
       "legendFormat": "stddev"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(aws_es_cpuutilization_maximum{domain_name=\"${cluster}\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "stddev(aws_es_cpuutilization_maximum{domain_name=\"${cluster}\"})",
       "legendFormat": "stddev"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "min(aws_es_free_storage_space_minimum{domain_name=\"${cluster}\"})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Indexing/search rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(aws_es_indexing_rate_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Indexing rate"
    },
    {
     "expr": "sum(aws_es_search_rate_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Search rate"
    }
   ]
  },
  {
   "title": "Threadpool",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max(aws_es_threadpool_search_rejected_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Search Rejected"
    },
    {
     "expr": "max(aws_es_threadpool_search_queue_maximum{domain_name=\"${cluster}\"}) by (domain_name)",
     "legendFormat": "Search queue"
    }
   ]
  }
 ]
}