{
 "title": "RDS Postgres",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dbinstance_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Engine Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_resources_exporter_rds_engineversion{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "{{ engine_version }}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_rds_write_latency_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{dbinstance_identifier=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Last backup",
   "type": "stat",
   "description": "How long ago last backup has been taken",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - aws_resources_exporter_rds_latestrestorabletime{dbinstance_identifier=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_maximum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Freeable memory"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "aws_resources_exporter_rds_maxconnections{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "max connections"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "aws_rds_write_latency_sum{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_sum{dbinstance_identifier=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "aws_rds_write_iops_average{dbinstance_identifier=\"${instance}\"}",
     "legendFormat": "write IOPS"
    }
   ]
  }
 ]
}