{
 "title": "Agent API",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "POST v2RegisterHost By Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST v2RegisterHost Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts\", method=\"POST\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "POST v2PostStepReply By Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST v2PostStepReply Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"POST\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GET v2GetNextSteps By status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GET v2GetNextSteps Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/hosts/{host_id}/instructions\", method=\"GET\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "POST V2UploadLogs By status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST V2UploadLogs Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}