{
 "title": "Validations",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Host - Cluster lifecycle",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_assisted_installer_host_validation_failed_after_success_before_installation[$__range:$__rate_interval])) by (hostValidationType)",
     "legendFormat": "{hostValidationType}}"
    }
   ]
  },
  {
   "title": "Host - On cluster deregistration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_assisted_installer_host_validation_is_in_failed_status_on_cluster_deletion[$__range:$__rate_interval])) by (hostValidationType)",
     "legendFormat": "{hostValidationType}}"
    }
   ]
  },
  {
   "title": "Cluster - Cluster lifecycle",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_assisted_installer_cluster_validation_failed_after_success_before_installation[$__range:$__rate_interval])) by (clusterValidationType)",
     "legendFormat": "{hostValidationType}}"
    }
   ]
  },
  {
   "title": "Cluster - On cluster deregistration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_assisted_installer_cluster_validation_is_in_failed_status_on_cluster_deletion[$__range:$__rate_interval])) by (clusterValidationType)",
     "legendFormat": "{hostValidationType}}"
    }
   ]
  }
 ]
}