{
 "title": "Weekly Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "OpenShift_Version", "label": "OpenShift_Version", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "All users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "# The Week of 3 Weeks Ago\n         "
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 }, "options": { "content": "# The Week of 2 Weeks Ago" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 }, "options": { "content": "# Previous Week\n\n         " } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 }, "options": { "content": "# Current Week\n\n         " } },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[28d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"}))[14d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain=~\".+\"}))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\"}))[7d:300s])"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[28d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[21d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[14d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})))[7d:300s])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[14d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[14d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[7d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[7d:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "# Installation Results\n         "
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[21d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[14d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".+\"}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[7d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[7d:$__rate_interval])",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", emailDomain=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{remailDomain=~\".+\", esult=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".+\", result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  { "title": "Internal users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 34 },
   "options": {
    "content": "# The Week of 3 Weeks Ago\n         "
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 34 }, "options": { "content": "# The Week of 2 Weeks Ago" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 34 }, "options": { "content": "# Previous Week\n\n         " } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 34 }, "options": { "content": "# Current Week\n\n         " } },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[28d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"}))[21d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"}))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:300s])"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[28d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[21d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[14d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[7d:300s])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[21d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[21d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[14d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "# Installation Results\n         "
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[21d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[7d:$__rate_interval])",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  { "title": "External users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 67 },
   "options": {
    "content": "# The Week of 3 Weeks Ago\n         "
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 67 }, "options": { "content": "# The Week of 2 Weeks Ago" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 67 }, "options": { "content": "# Previous Week\n\n         " } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 67 }, "options": { "content": "# Current Week\n\n         " } },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[28d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:300s])) - (increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters With Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_hosts{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:300s])"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[28d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[21d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[21d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[14d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[14d:300s])) - (increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[7d:300s]))"
    }
   ]
  },
  {
   "title": "Clusters Generated ISO (Unique Per Cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by(clusterId)(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"})))[7d:300s])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 81 },
   "options": {
    "content": "# Installation Results\n         "
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[7d:$__rate_interval])",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 86 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 86 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 86 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 86 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"installed\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"canceled\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"error\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}