{
 "title": "Basic Cluster operation",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "POST Cluster By Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST Cluster Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters\", method=\"POST\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GET Cluster By Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GET Cluster Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GET GetInfraEnvDownloadURL By status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GET GetInfraEnvDownloadURL Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/infra-envs/{infra_env_id}/downloads/image-url\", method=\"GET\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "POST V2UploadLogs By status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST V2UploadLogs Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v2/clusters/{cluster_id}/logs\", method=\"POST\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Host network latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_assisted_installer_host_network_latency_in_ms_bucket[5m])) by (le))\n",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(service_assisted_installer_host_network_latency_in_ms_bucket[5m])) by (le))\n",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(service_assisted_installer_host_network_latency_in_ms_bucket[5m])) by (le))\n",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(service_assisted_installer_host_network_latency_in_ms_bucket[5m])) by (le))\n",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(service_assisted_installer_host_network_latency_in_ms_sum[5m])) by (handler) / sum(rate(service_assisted_installer_host_network_latency_in_ms_count[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Packet loss percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (le))\n",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (le))\n",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (le))\n",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (le))\n",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (handler) / sum(rate(service_assisted_installer_packet_loss_percentage_bucket[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}