{
 "title": "Cluster Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "clusterId", "label": "clusterId", "query": "<Enter clusterId Here>" }
  ]
 },
 "panels": [
  { "title": "Cluster Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Cluster Application Metrics will show absolute numbers, not increases over time."
   }
  },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_creations{clusterId=\"$clusterId\"})",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started{clusterId=\"$clusterId\"})",
     "legendFormat": "Installation started"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=\"$clusterId\", result=\"installed\"})",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=\"$clusterId\", result=\"error\"})",
     "legendFormat": "Installation error"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=\"$clusterId\", result=\"canceled\"})",
     "legendFormat": "Installation canceled"
    }
   ]
  },
  {
   "title": "Email Domain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (emailDomain)(service_assisted_installer_cluster_installation_seconds_count{clusterId=\"$clusterId\"})",
     "legendFormat": "{{emailDomain}}"
    }
   ]
  },
  {
   "title": "Installations success rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=\"$clusterId\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_hosts{clusterId=\"$clusterId\"})"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "failues", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (role)(service_assisted_installer_cluster_hosts{clusterId=\"$clusterId\", result=\"Failed\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Average Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=\"$clusterId\",result=\"Done\"}) / sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=\"$clusterId\",result=\"Done\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Install Attempts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started{clusterId=\"$clusterId\"})",
     "legendFormat": "attempts"
    }
   ]
  },
  {
   "title": "Hosts By Vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_hosts{clusterId=\"$clusterId\",vendor=~\".+\",product=~\".+\"}) by (vendor,product)",
     "legendFormat": "{{vendor}} {{product}}"
    }
   ]
  },
  { "title": "Cluster Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Request Rate By Code",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{clusterId=\"$clusterId\",endpoint=\"assisted-svc\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Request Rate By Handler",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{clusterId=\"$clusterId\",endpoint=\"assisted-svc\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "400 Codes By Handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{clusterId=\"$clusterId\",endpoint=\"assisted-svc\", code=~\"4.*\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "500 Codes By Handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{clusterId=\"clusterId\",endpoint=\"assisted-svc\", code=~\"5.*\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}