{
 "title": "Assisted Events Scrape",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Events Scraper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Cpu usage avg"
    },
    {
     "expr": "stddev(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Cpu usage stddev"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}[$interval]))",
     "legendFormat": "Throttling"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"${namespace}\",container=\"assisted-events-scrape\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"assisted-installer-${environment}\",container=\"assisted-events-scrape\",resource=\"memory\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"assisted-installer-${environment}\",container=\"assisted-events-scrape\",resource=\"memory\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"${namespace}\",container=\"assisted-events-scrape\"}) by (pod)",
     "legendFormat": "Restarts {{ pod }}"
    },
    {}
   ]
  },
  {
   "title": "RX/TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\",pod=~\"assisted-events-scrape.*\"}[$interval])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\",pod=~\"assisted-events-scrape.*\"}[$interval])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}