{
 "title": "General Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "OpenShift_Version", "label": "OpenShift_Version", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "All Clusters & Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "increase(count(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))[$__range:$__rate_interval])",
     "legendFormat": "ISO generated"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation started"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"installed\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"error\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation error"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"canceled\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation canceled"
    }
   ]
  },
  {
   "title": "Average Hosts Per Cluster",
   "type": "stat",
   "description": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above.",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "Hosts"
    },
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "Clusters"
    },
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]) + 1) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Installations success rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 5 },
   "options": {
    "content": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above."
   }
  },
  {
   "title": "Average Install Attempts Per  Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Average Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"Done\"})[$__range:$__rate_interval]) / increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"Done\"})[$__range:$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Cluster Count by emailDomain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(count by (emailDomain)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"})[$__range:$__rate_interval]) + 1",
     "legendFormat": "{{emailDomain}}"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "failues", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (role)(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"Failed\"})[$__range:$__rate_interval])",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Hosts By Vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (vendor,product)(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "{{vendor}} {{product}}"
    }
   ]
  },
  { "title": "Internal Clusters & Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "increase(count(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"}))[$__range:$__rate_interval])",
     "legendFormat": "ISO generated"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation started"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"installed\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"error\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation error"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"canceled\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation canceled"
    }
   ]
  },
  {
   "title": "Average Hosts Per Cluster",
   "type": "stat",
   "description": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above.",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "Hosts"
    },
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[$__range:$__rate_interval])",
     "legendFormat": "Clusters"
    },
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]) + 1) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",}))[$__range:$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Installations success rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 26 },
   "options": {
    "content": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above."
   }
  },
  {
   "title": "Average Install Attempts Per  Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[$__range:$__rate_interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\"}))[$__range:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Average Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"Done\"})[$__range:$__rate_interval]) / increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\",result=\"Done\"})[$__range:$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Hosts By Vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (vendor,product)(service_assisted_installer_cluster_hosts{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain=~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "{{vendor}} {{product}}"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "failues", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (role)(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".*redhat.com.*|.*ibm.com.*\", result=\"Failed\"})[$__range:$__rate_interval])",
     "legendFormat": "{{role}}"
    }
   ]
  },
  { "title": "External Clusters & Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "increase(count(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\"}))[$__range:$__rate_interval])",
     "legendFormat": "ISO generated"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation started"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"installed\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"error\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation error"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\", result=\"canceled\"})[$__range:$__rate_interval])",
     "legendFormat": "Installation canceled"
    }
   ]
  },
  {
   "title": "Average Hosts Per Cluster",
   "type": "stat",
   "description": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above.",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "Hosts"
    },
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[$__range:$__rate_interval])",
     "legendFormat": "Clusters"
    },
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]) + 1) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[$__range:$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Installations success rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 47 },
   "options": {
    "content": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above."
   }
  },
  {
   "title": "Average Install Attempts Per  Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[$__range:$__rate_interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",}))[$__range:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\",})[$__range:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Average Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"Done\"})[$__range:$__rate_interval]) / increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",result=\"Done\"})[$__range:$__rate_interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Hosts By Vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (vendor,product)(service_assisted_installer_cluster_hosts{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\",clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval])",
     "legendFormat": "{{vendor}} {{product}}"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "failues", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (role)(service_assisted_installer_cluster_hosts{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain!~\".*redhat.com.*|.*ibm.com.*\",emailDomain=~\".+\", result=\"Failed\"})[$__range:$__rate_interval])",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}