apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    capability.openshift.io/name: baremetal
  name: baremetal
spec: {}
status:
 versions:
  - name: operator
    version: 4.11.0-0.nightly-2022-06-15-222801
