apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-agent-cluster-install
  namespace: spoke-cluster
spec:
  apiVIP: 1.2.3.8
  clusterDeploymentRef:
    name: test-cluster
  imageSetRef:
    name: openshift-v4.8.0
  ingressVIP: 1.2.3.9
  platformType: BareMetal
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 3
 #sshPublicKey: ssh-rsa your-public-key-here (optional)
  # By default, SMT (or hyperthreading) is enabled to increase the performance of your machines' cores.
  # Therefore, you can omit this section unless you wish to disable hyperthreading.
  # You can disable SMT by setting the parameter value to 'Disabled'. Then, you must disable it in all cluster machines;
  # this includes both control plane and compute machines.
  compute:
  - hyperthreading: Enabled
    name: worker
  controlPlane:
    hyperthreading: Enabled
    name: master
