apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: {{ .Operator.Namespace }}
spec:
  logLevel: Normal
  mode: "Automatic"
  operatorLogLevel: Normal
  profiles:
    - KubeVirtRelieveAndMigrate
  deschedulingIntervalSeconds: 60
  managementState: Managed 