// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// ListSupportedOperatorsOKCode is the HTTP code returned for type ListSupportedOperatorsOK
const ListSupportedOperatorsOKCode int = 200

/*ListSupportedOperatorsOK Success.

swagger:response listSupportedOperatorsOK
*/
type ListSupportedOperatorsOK struct {

	/*
	  In: Body
	*/
	Payload models.MonitoredOperatorsList `json:"body,omitempty"`
}

// NewListSupportedOperatorsOK creates ListSupportedOperatorsOK with default headers values
func NewListSupportedOperatorsOK() *ListSupportedOperatorsOK {

	return &ListSupportedOperatorsOK{}
}

// WithPayload adds the payload to the list supported operators o k response
func (o *ListSupportedOperatorsOK) WithPayload(payload models.MonitoredOperatorsList) *ListSupportedOperatorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list supported operators o k response
func (o *ListSupportedOperatorsOK) SetPayload(payload models.MonitoredOperatorsList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSupportedOperatorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.MonitoredOperatorsList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListSupportedOperatorsUnauthorizedCode is the HTTP code returned for type ListSupportedOperatorsUnauthorized
const ListSupportedOperatorsUnauthorizedCode int = 401

/*ListSupportedOperatorsUnauthorized Unauthorized.

swagger:response listSupportedOperatorsUnauthorized
*/
type ListSupportedOperatorsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewListSupportedOperatorsUnauthorized creates ListSupportedOperatorsUnauthorized with default headers values
func NewListSupportedOperatorsUnauthorized() *ListSupportedOperatorsUnauthorized {

	return &ListSupportedOperatorsUnauthorized{}
}

// WithPayload adds the payload to the list supported operators unauthorized response
func (o *ListSupportedOperatorsUnauthorized) WithPayload(payload *models.InfraError) *ListSupportedOperatorsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list supported operators unauthorized response
func (o *ListSupportedOperatorsUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSupportedOperatorsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSupportedOperatorsForbiddenCode is the HTTP code returned for type ListSupportedOperatorsForbidden
const ListSupportedOperatorsForbiddenCode int = 403

/*ListSupportedOperatorsForbidden Forbidden.

swagger:response listSupportedOperatorsForbidden
*/
type ListSupportedOperatorsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewListSupportedOperatorsForbidden creates ListSupportedOperatorsForbidden with default headers values
func NewListSupportedOperatorsForbidden() *ListSupportedOperatorsForbidden {

	return &ListSupportedOperatorsForbidden{}
}

// WithPayload adds the payload to the list supported operators forbidden response
func (o *ListSupportedOperatorsForbidden) WithPayload(payload *models.InfraError) *ListSupportedOperatorsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list supported operators forbidden response
func (o *ListSupportedOperatorsForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSupportedOperatorsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSupportedOperatorsInternalServerErrorCode is the HTTP code returned for type ListSupportedOperatorsInternalServerError
const ListSupportedOperatorsInternalServerErrorCode int = 500

/*ListSupportedOperatorsInternalServerError Error.

swagger:response listSupportedOperatorsInternalServerError
*/
type ListSupportedOperatorsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListSupportedOperatorsInternalServerError creates ListSupportedOperatorsInternalServerError with default headers values
func NewListSupportedOperatorsInternalServerError() *ListSupportedOperatorsInternalServerError {

	return &ListSupportedOperatorsInternalServerError{}
}

// WithPayload adds the payload to the list supported operators internal server error response
func (o *ListSupportedOperatorsInternalServerError) WithPayload(payload *models.Error) *ListSupportedOperatorsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list supported operators internal server error response
func (o *ListSupportedOperatorsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSupportedOperatorsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
