---
parameters:
- name: ASSISTED_SERVICE_IMAGE
  value: quay.io/app-sre/assisted-service
- name: IMAGE_TAG
  value: ''
  required: true
- name: SERVICE_BASE_URL
  value: ''
  required: true
- name: BASE_DNS_DOMAINS # example: name1:id1/provider1,name2:id2/provider2
  value: ''
- name: OPENSHIFT_VERSIONS
  value: '{"4.6":{"display_name":"4.6.16","release_version":"4.6.16","release_image":"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img","rhcos_version":"46.82.202012051820-0","support_level":"production"},"4.7":{"display_name":"4.7.18","release_version":"4.7.18","release_image":"quay.io/openshift-release-dev/ocp-release:4.7.18-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-4.7.13-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live-rootfs.x86_64.img","rhcos_version":"47.83.202105220305-0","support_level":"production","default":true},"4.8":{"display_name":"4.8.0-rc.3","release_version":"4.8.0-rc.3","release_image":"quay.io/openshift-release-dev/ocp-release:4.8.0-rc.3-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.8.0-rc.3/rhcos-4.8.0-rc.3-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.8.0-rc.3/rhcos-live-rootfs.x86_64.img","rhcos_version":"48.84.202107040900-0","support_level":"beta"}}' # openshift version
  required: false
- name: JWKS_URL # example https://example.com/.well-known/jwks.json
  value: ''
  required: true
- name: ALLOWED_DOMAINS
  value: ''
  required: true
- name: AUTH_TYPE
  value: ''
  required: true
- name: WITH_AMS_SUBSCRIPTIONS
  value: ''
  required: true
- name: OCM_BASE_URL
  value: ''
  required: true
- name: OCM_LOG_LEVEL
  value: "info"
  required: false
- name: S3_USE_SSL
  value: "true"
- name: HW_VALIDATOR_REQUIREMENTS
  value: ''
  required: true
- name: INSTALLER_IMAGE
  value: ''
  required: true
- name: CONTROLLER_IMAGE
  value: ''
  required: true
- name: AGENT_DOCKER_IMAGE
  value: ''
  required: true
- name: INSTALL_RH_CA
  value: "false"
  required: true
- name: REGISTRY_CREDS
  value: ""
- name: LOG_LEVEL
  value: "info"
  required: true
- name: REPLICAS_COUNT
  value: "3"
- name: RELEASE_TAG
  value: ''
- name: AGENT_TIMEOUT_START
  value: '3m'
- name: SUPPORT_L2
  value: "true"
- name: ADMIN_USERS
  value: ''
  required: false
- name: PUBLIC_CONTAINER_REGISTRIES
  value: ""
- name: CHECK_CLUSTER_VERSION
  value: "true"
- name: IPV6_SUPPORT
  value: "true"
  required: false
- name: ENABLE_SINGLE_NODE_DNSMASQ
  value: "true"
  required: false
- name: ENABLE_DEREGISTER_INACTIVE_GC
  value: "false"
- name: ENABLE_DELETE_UNREGISTER_GC
  value: "true"
- name: DB_MAX_IDLE_CONNECTIONS
  value: "50"
  required: false
- name: DB_MAX_OPEN_CONNECTIONS
  value: "600"
- name: DISABLED_HOST_VALIDATIONS
  value: ""
  required: false
- name: DISABLED_STEPS
  value: ""
  required: false
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-service
  spec:
    selector:
      matchLabels:
        app: assisted-service
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          app: assisted-service
      spec:
        serviceAccountName: assisted-service
        containers:
          - name: assisted-service
            image: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 500m
                memory: 2000Mi
              requests:
                cpu: 300m
                memory: 400Mi
            ports:
              - name: assisted-svc
                containerPort: 8090
            livenessProbe:
              httpGet:
                path: /health
                port: 8090
              initialDelaySeconds: 30
            readinessProbe:
              httpGet:
                path: /ready
                port: 8090
            env:
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: assisted-installer-s3
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: assisted-installer-s3
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: assisted-installer-s3
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: assisted-installer-s3
              - name: S3_ENDPOINT_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-s3
              - name: AWS_SECRET_ACCESS_KEY_PUBLIC
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: assisted-installer-public-s3
              - name: AWS_ACCESS_KEY_ID_PUBLIC
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: assisted-installer-public-s3
              - name: S3_REGION_PUBLIC
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: assisted-installer-public-s3
              - name: S3_BUCKET_PUBLIC
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: assisted-installer-public-s3
              - name: S3_ENDPOINT_URL_PUBLIC
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-public-s3
              - name: S3_USE_SSL
                value: ${S3_USE_SSL}
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    key: db.host
                    name: assisted-installer-rds
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: db.name
                    name: assisted-installer-rds
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    key: db.password
                    name: assisted-installer-rds
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    key: db.port
                    name: assisted-installer-rds
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    key: db.user
                    name: assisted-installer-rds
              - name: OCM_SERVICE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientId
                    name: assisted-installer-sso
              - name: OCM_SERVICE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientSecret
                    name: assisted-installer-sso
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: SERVICE_BASE_URL
                value: ${SERVICE_BASE_URL}
              - name: BASE_DNS_DOMAINS
                value: ${BASE_DNS_DOMAINS}
              - name: OPENSHIFT_VERSIONS
                value: ${OPENSHIFT_VERSIONS}
              - name: AUTH_TYPE
                value: ${AUTH_TYPE}
              - name: WITH_AMS_SUBSCRIPTIONS
                value: ${WITH_AMS_SUBSCRIPTIONS}
              - name: JWKS_URL
                value: ${JWKS_URL}
              - name: ALLOWED_DOMAINS
                value: ${ALLOWED_DOMAINS}
              - name: OCM_BASE_URL
                value: ${OCM_BASE_URL}
              - name: OCM_LOG_LEVEL
                value: ${OCM_LOG_LEVEL}
              - name: HW_VALIDATOR_REQUIREMENTS
                value: ${HW_VALIDATOR_REQUIREMENTS}
              - name: INSTALLER_IMAGE
                value: ${INSTALLER_IMAGE}
              - name: SELF_VERSION
                value: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
              - name: CONTROLLER_IMAGE
                value: ${CONTROLLER_IMAGE}
              - name: AGENT_DOCKER_IMAGE
                value: ${AGENT_DOCKER_IMAGE}
              - name: SUPPORT_L2
                value: ${SUPPORT_L2}
              - name: LOG_LEVEL
                value: ${LOG_LEVEL}
              - name: INSTALL_RH_CA
                value: ${INSTALL_RH_CA}
              - name: REGISTRY_CREDS
                value: ${REGISTRY_CREDS}
              - name: RELEASE_TAG
                value: ${RELEASE_TAG}
              - name: AGENT_TIMEOUT_START
                value: ${AGENT_TIMEOUT_START}
              - name: AWS_SHARED_CREDENTIALS_FILE
                value: /etc/.aws/credentials
              - name: ADMIN_USERS
                value: ${ADMIN_USERS}
              - name: PUBLIC_CONTAINER_REGISTRIES
                value: ${PUBLIC_CONTAINER_REGISTRIES}
              - name: CHECK_CLUSTER_VERSION
                value: ${CHECK_CLUSTER_VERSION}
              - name: IPV6_SUPPORT
                value: ${IPV6_SUPPORT}
              - name: ENABLE_SINGLE_NODE_DNSMASQ
                value: ${ENABLE_SINGLE_NODE_DNSMASQ}
              - name: DB_MAX_IDLE_CONNECTIONS
                value: ${DB_MAX_IDLE_CONNECTIONS}
              - name: DB_MAX_OPEN_CONNECTIONS
                value: ${DB_MAX_OPEN_CONNECTIONS}
              - name: DISABLED_HOST_VALIDATIONS
                value: ${DISABLED_HOST_VALIDATIONS}
              - name: DISABLED_STEPS
                value: ${DISABLED_STEPS}
            volumeMounts:
              - name: route53-creds
                mountPath: "/etc/.aws"
                readOnly: true
        volumes:
          - name: route53-creds
            secret:
              secretName: route53-creds
              optional: true
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: assisted-service
    name: assisted-service
  spec:
    ports:
      - name: assisted-svc
        port: 8090
        protocol: TCP
        targetPort: 8090
    selector:
      app: assisted-service
