---
parameters:
- name: ASSISTED_SERVICE_IMAGE
  value: quay.io/app-sre/assisted-service
- name: IMAGE_TAG
  value: ''
  required: true
- name: SERVICE_BASE_URL
  value: ''
  required: true
- name: IMAGE_SERVICE_BASE_URL
  value: ""
- name: BASE_DNS_DOMAINS # example: name1:id1/provider1,name2:id2/provider2
  value: ''
  required: false
- name: OS_IMAGES
  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso","version":"48.84.202109241901-0"},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.40/rhcos-4.9.40-x86_64-live.x86_64.iso","version":"49.84.202206171736-0"},{"openshift_version":"4.10","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.16/rhcos-4.10.16-x86_64-live.x86_64.iso","version":"410.84.202205191234-0"},{"openshift_version":"4.10","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.10/4.10.16/rhcos-4.10.16-aarch64-live.aarch64.iso","version":"410.84.202205191023-0"},{"openshift_version":"4.11","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/4.11.0/rhcos-4.11.0-x86_64-live.x86_64.iso","version":"411.86.202207150124-0"},{"openshift_version":"4.11","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.11/4.11.0/rhcos-4.11.0-aarch64-live.aarch64.iso","version":"411.86.202207130959-0"},{"openshift_version":"4.12","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/4.12.0-ec.2/rhcos-4.12.0-ec.2-x86_64-live.x86_64.iso","version":"412.86.202208101039-0"},{"openshift_version":"4.12","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/pre-release/4.12.0-ec.2/rhcos-4.12.0-ec.2-aarch64-live.aarch64.iso","version":"412.86.202208101040-0"}]' # os images
  required: false
- name: RELEASE_IMAGES
  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.8.48-x86_64","version":"4.8.48"},{"openshift_version":"4.9","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.9.46-x86_64","version":"4.9.46"},{"openshift_version":"4.10","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.28-x86_64","version":"4.10.28"},{"openshift_version":"4.10","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.28-aarch64","version":"4.10.28"},{"openshift_version":"4.11","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.0-x86_64","version":"4.11.0","default":true},{"openshift_version":"4.11","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.0-aarch64","version":"4.11.0"},{"openshift_version":"4.11-multi","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.0-multi","version":"4.11.0-multi"},{"openshift_version":"4.12","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.12.0-ec.2-x86_64","support_level":"beta","version":"4.12.0-ec.2"},{"openshift_version":"4.12","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.12.0-ec.2-aarch64","support_level":"beta","version":"4.12.0-ec.2"}]' # release images
  required: false
- name: MUST_GATHER_IMAGES
  value: '{"4.8":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5","ocs":"registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.8","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8:v4.8"},"4.9":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v4.9.3","ocs":"registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.9","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8:v4.9"},"4.10":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v4.10.0","ocs":"registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.10","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8:v4.10"}}' # must-gather images
  required: false
- name: JWKS_URL # example https://example.com/.well-known/jwks.json
  value: ''
  required: true
- name: ALLOWED_DOMAINS
  value: ''
  required: true
- name: AUTH_TYPE
  value: ''
  required: true
- name: OCM_BASE_URL
  value: ''
  required: true
- name: OCM_LOG_LEVEL
  value: "info"
  required: false
- name: S3_USE_SSL
  value: "true"
- name: ENABLE_AUTO_ASSIGN
  value: "true"
  required: false
- name: HW_VALIDATOR_REQUIREMENTS
  value: ''
  required: true
- name: INSTALLER_IMAGE
  value: ''
  required: true
- name: CONTROLLER_IMAGE
  value: ''
  required: true
- name: AGENT_DOCKER_IMAGE
  value: ''
  required: true
- name: INSTALL_RH_CA
  value: "false"
  required: true
- name: REGISTRY_CREDS
  value: ""
- name: LOG_LEVEL
  value: "info"
  required: true
- name: REPLICAS_COUNT
  value: "3"
- name: RELEASE_TAG
  value: ''
- name: AGENT_TIMEOUT_START
  value: '3m'
- name: ADMIN_USERS
  value: ''
  required: false
- name: PUBLIC_CONTAINER_REGISTRIES
  value: ""
- name: CHECK_CLUSTER_VERSION
  value: "true"
- name: IPV6_SUPPORT
  value: "true"
  required: false
- name: ENABLE_SINGLE_NODE_DNSMASQ
  value: "true"
  required: false
- name: DISK_ENCRYPTION_SUPPORT
  value: "true"
  required: false
- name: ENABLE_DEREGISTER_INACTIVE_GC
  value: "false"
- name: ENABLE_DELETE_UNREGISTER_GC
  value: "true"
- name: DB_MAX_IDLE_CONNECTIONS
  value: "50"
  required: false
- name: DB_MAX_OPEN_CONNECTIONS
  value: "600"
- name: DISABLED_HOST_VALIDATIONS
  value: ""
  required: false
- name: LIVENESS_VALIDATION_TIMEOUT
  value: "5m"
  required: false
- name: DISABLED_STEPS
  value: ""
  required: false
- name: MAX_GC_INFRAENVS_PER_INTERVAL
  value: "100"
  required: false
- name: INFRAENV_DELETED_INACTIVE_AFTER
  value: "480h"
  required: false
- name: INFRAENV_DELETION_WORKER_INTERVAL
  value: "1h"
  required: false
- name: CNV_SNO_INSTALL_HPP
  value: "true"
  required: false
- name: ENABLE_ORG_TENANCY
  value: "false"
  required: false
- name: ENABLE_ORG_BASED_FEATURE_GATES
  value: "false"
  required: false
- name: MEMORY_LIMIT
  value: "2.55G"
  required: false
- name: CPU_LIMIT
  value: "500m"
  required: false
- name: MEMORY_REQUEST
  value: "1.7G"
  required: false
- name: CPU_REQUEST
  value: "300m"
  required: false
- name: ISO_IMAGE_TYPE
  value: "minimal-iso"
  required: false
- name: ENABLE_UPGRADE_AGENT
  value: "false"
  required: false
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-service
  spec:
    selector:
      matchLabels:
        app: assisted-service
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          app: assisted-service
      spec:
        serviceAccountName: assisted-service
        containers:
          - name: assisted-service
            image: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
            ports:
              - name: assisted-svc
                containerPort: 8090
            livenessProbe:
              httpGet:
                path: /health
                port: 8090
              initialDelaySeconds: 30
            readinessProbe:
              httpGet:
                path: /ready
                port: 8090
            env:
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: assisted-installer-s3
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: assisted-installer-s3
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: assisted-installer-s3
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: assisted-installer-s3
              - name: S3_ENDPOINT_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-s3
              - name: S3_USE_SSL
                value: ${S3_USE_SSL}
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    key: db.host
                    name: assisted-installer-rds
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: db.name
                    name: assisted-installer-rds
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    key: db.password
                    name: assisted-installer-rds
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    key: db.port
                    name: assisted-installer-rds
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    key: db.user
                    name: assisted-installer-rds
              - name: OCM_SERVICE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientId
                    name: assisted-installer-sso
              - name: OCM_SERVICE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientSecret
                    name: assisted-installer-sso
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: SERVICE_BASE_URL
                value: ${SERVICE_BASE_URL}
              - name: IMAGE_SERVICE_BASE_URL
                value: ${IMAGE_SERVICE_BASE_URL}
              - name: BASE_DNS_DOMAINS
                value: ${BASE_DNS_DOMAINS}
              - name: OS_IMAGES
                value: ${OS_IMAGES}
              - name: RELEASE_IMAGES
                value: ${RELEASE_IMAGES}
              - name: MUST_GATHER_IMAGES
                value: ${MUST_GATHER_IMAGES}
              - name: AUTH_TYPE
                value: ${AUTH_TYPE}
              - name: JWKS_URL
                value: ${JWKS_URL}
              - name: ALLOWED_DOMAINS
                value: ${ALLOWED_DOMAINS}
              - name: OCM_BASE_URL
                value: ${OCM_BASE_URL}
              - name: OCM_LOG_LEVEL
                value: ${OCM_LOG_LEVEL}
              - name: HW_VALIDATOR_REQUIREMENTS
                value: ${HW_VALIDATOR_REQUIREMENTS}
              - name: INSTALLER_IMAGE
                value: ${INSTALLER_IMAGE}
              - name: SELF_VERSION
                value: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
              - name: CONTROLLER_IMAGE
                value: ${CONTROLLER_IMAGE}
              - name: AGENT_DOCKER_IMAGE
                value: ${AGENT_DOCKER_IMAGE}
              - name: LOG_LEVEL
                value: ${LOG_LEVEL}
              - name: INSTALL_RH_CA
                value: ${INSTALL_RH_CA}
              - name: REGISTRY_CREDS
                value: ${REGISTRY_CREDS}
              - name: RELEASE_TAG
                value: ${RELEASE_TAG}
              - name: AGENT_TIMEOUT_START
                value: ${AGENT_TIMEOUT_START}
              - name: AWS_SHARED_CREDENTIALS_FILE
                value: /etc/.aws/credentials
              - name: ADMIN_USERS
                value: ${ADMIN_USERS}
              - name: LIVENESS_VALIDATION_TIMEOUT
                value: ${LIVENESS_VALIDATION_TIMEOUT}
              - name: PUBLIC_CONTAINER_REGISTRIES
                value: ${PUBLIC_CONTAINER_REGISTRIES}
              - name: CHECK_CLUSTER_VERSION
                value: ${CHECK_CLUSTER_VERSION}
              - name: IPV6_SUPPORT
                value: ${IPV6_SUPPORT}
              - name: ENABLE_SINGLE_NODE_DNSMASQ
                value: ${ENABLE_SINGLE_NODE_DNSMASQ}
              - name: DB_MAX_IDLE_CONNECTIONS
                value: ${DB_MAX_IDLE_CONNECTIONS}
              - name: DB_MAX_OPEN_CONNECTIONS
                value: ${DB_MAX_OPEN_CONNECTIONS}
              - name: DISABLED_HOST_VALIDATIONS
                value: ${DISABLED_HOST_VALIDATIONS}
              - name: DISABLED_STEPS
                value: ${DISABLED_STEPS}
              - name: ENABLE_AUTO_ASSIGN
                value: ${ENABLE_AUTO_ASSIGN}
              - name: DISK_ENCRYPTION_SUPPORT
                value: ${DISK_ENCRYPTION_SUPPORT}
              - name: MAX_GC_INFRAENVS_PER_INTERVAL
                value: ${MAX_GC_INFRAENVS_PER_INTERVAL}
              - name: INFRAENV_DELETION_WORKER_INTERVAL
                value: ${INFRAENV_DELETION_WORKER_INTERVAL}
              - name: INFRAENV_DELETED_INACTIVE_AFTER
                value: ${INFRAENV_DELETED_INACTIVE_AFTER}
              - name: CNV_SNO_INSTALL_HPP
                value: ${CNV_SNO_INSTALL_HPP}
              - name: ENABLE_ORG_TENANCY
                value: ${ENABLE_ORG_TENANCY}
              - name: ENABLE_ORG_BASED_FEATURE_GATES
                value: ${ENABLE_ORG_BASED_FEATURE_GATES}
              - name: ISO_IMAGE_TYPE
                value: ${ISO_IMAGE_TYPE}
              - name: ENABLE_UPGRADE_AGENT
                value: ${ENABLE_UPGRADE_AGENT}
            volumeMounts:
              - name: route53-creds
                mountPath: "/etc/.aws"
                readOnly: true
        volumes:
          - name: route53-creds
            secret:
              secretName: route53-creds
              optional: true
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: assisted-service
    name: assisted-service
  spec:
    ports:
      - name: assisted-svc
        port: 8090
        protocol: TCP
        targetPort: 8090
    selector:
      app: assisted-service
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app: assisted-service
    name: assisted-service
  spec:
    minAvailable: 2
    selector:
      matchLabels:
        app: assisted-service
