---
parameters:
- name: JOBID
  generate: expression
  from: "[0-9a-f]{7}"
apiVersion: v1
kind: Template
metadata:
  name: assisted-service-post-deploy
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: assisted-service-post-deploy-${JOBID}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: quay.io/app-sre/centos:8
            imagePullPolicy: Always
            name: assisted-service-post-deploy
            command:
              - curl
            args:
              - -X
              - POST
              - --user
              - $(USER):$(TOKEN)
              - $(URL)?OFFLINE_TOKEN_CRED=$(OFFLINE_TOKEN_CRED)&PULL_SECRET_CRED=$(PULL_SECRET_CRED)&ASSISTED_SERVICE_URL=$(ASSISTED_SERVICE_URL)
            env:
              - name: URL
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: URL
              - name: PULL_SECRET_CRED
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: PULL_SECRET_CRED
              - name: OFFLINE_TOKEN_CRED
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: OFFLINE_TOKEN_CRED
              - name: ASSISTED_SERVICE_URL
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: ASSISTED_SERVICE_URL
              - name: USER
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: USER
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: jenkins
                    key: TOKEN
