---
parameters:
- name: ASSISTED_SERVICE_IMAGE
  value: quay.io/app-sre/assisted-service
- name: IMAGE_TAG
  value: ''
  required: true
- name: SERVICE_BASE_URL
  value: ''
  required: true
- name: BASE_DNS_DOMAINS # example: name1:id1/provider1,name2:id2/provider2
  value: ''
  required: true
- name: OPENSHIFT_INSTALL_RELEASE_IMAGE
  value: ''
  required: true
- name: JWKS_URL # example https://example.com/.well-known/jwks.json
  value: ''
  required: true
- name: ALLOWED_DOMAINS
  value: ''
  required: true
- name: ENABLE_AUTH
  value: ''
  required: true
- name: OCM_BASE_URL
  value: ''
  required: true
- name: S3_USE_SSL
  value: "true"
- name: IMAGE_BUILDER
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_RAM_GIB_MASTER
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_CPU_CORES_MASTER
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_CPU_CORES_WORKER
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_RAM_GIB_WORKER
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_CPU_CORES
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_RAM_GIB
  value: ''
  required: true
- name: HW_VALIDATOR_MIN_DISK_SIZE_GIB
  value: ''
  required: true
- name: IGNITION_GENERATE_IMAGE
  value: ''
  required: true
- name: INSTALLER_IMAGE
  value: ''
  required: true
- name: CONTROLLER_IMAGE
  value: ''
  required: true
- name: AGENT_DOCKER_IMAGE
  value: ''
  required: true
- name: CONNECTIVITY_CHECK_IMAGE
  value: ''
  required: true
- name: INVENTORY_IMAGE
  value: ''
  required: true
- name: FREE_ADDRESSES_IMAGE
  value: ''
  required: true
- name: DHCP_LEASE_ALLOCATOR_IMAGE
  value: ''
  required: true
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-service
  spec:
    selector:
      matchLabels:
        app: assisted-service
    replicas: 1
    template:
      metadata:
        labels:
          app: assisted-service
      spec:
        serviceAccountName: assisted-service
        containers:
          - name: assisted-service
            image: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 200m
                memory: 2000Mi
              requests:
                cpu: 100m
                memory: 400Mi
            ports:
              - name: assisted-svc
                containerPort: 8090
            livenessProbe:
              httpGet:
                path: /health
                port: 8090
            readinessProbe:
              httpGet:
                path: /ready
                port: 8090
            env:
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: assisted-installer-s3
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: assisted-installer-s3
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: assisted-installer-s3
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: assisted-installer-s3
              - name: S3_ENDPOINT_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-s3
              - name: S3_USE_SSL
                value: ${S3_USE_SSL}
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    key: db.host
                    name: assisted-installer-rds
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: db.name
                    name: assisted-installer-rds
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    key: db.password
                    name: assisted-installer-rds
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    key: db.port
                    name: assisted-installer-rds
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    key: db.user
                    name: assisted-installer-rds
              - name: OCM_SERVICE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientId
                    name: assisted-installer-sso
              - name: OCM_SERVICE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: ocm-service.clientSecret
                    name: assisted-installer-sso
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: SERVICE_BASE_URL
                value: ${SERVICE_BASE_URL}
              - name: BASE_DNS_DOMAINS
                value: ${BASE_DNS_DOMAINS}
              - name: OPENSHIFT_INSTALL_RELEASE_IMAGE
                value: ${OPENSHIFT_INSTALL_RELEASE_IMAGE}
              - name: ENABLE_AUTH
                value: ${ENABLE_AUTH}
              - name: JWKS_URL
                value: ${JWKS_URL}
              - name: ALLOWED_DOMAINS
                value: ${ALLOWED_DOMAINS}
              - name: OCM_BASE_URL
                value: ${OCM_BASE_URL}
              - name: IMAGE_BUILDER
                value: ${IMAGE_BUILDER}:${IMAGE_TAG}
              - name: HW_VALIDATOR_MIN_RAM_GIB_MASTER
                value: ${HW_VALIDATOR_MIN_RAM_GIB_MASTER}
              - name: HW_VALIDATOR_MIN_CPU_CORES_MASTER
                value: ${HW_VALIDATOR_MIN_CPU_CORES_MASTER}
              - name: HW_VALIDATOR_MIN_CPU_CORES_WORKER
                value: ${HW_VALIDATOR_MIN_CPU_CORES_WORKER}
              - name: HW_VALIDATOR_MIN_RAM_GIB_WORKER
                value: ${HW_VALIDATOR_MIN_RAM_GIB_WORKER}
              - name: HW_VALIDATOR_MIN_CPU_CORES
                value: ${HW_VALIDATOR_MIN_CPU_CORES}
              - name: HW_VALIDATOR_MIN_RAM_GIB
                value: ${HW_VALIDATOR_MIN_RAM_GIB}
              - name: HW_VALIDATOR_MIN_DISK_SIZE_GIB
                value: ${HW_VALIDATOR_MIN_DISK_SIZE_GIB}
              - name: IGNITION_GENERATE_IMAGE
                value: ${IGNITION_GENERATE_IMAGE}
              - name: INSTALLER_IMAGE
                value: ${INSTALLER_IMAGE}
              - name: SELF_VERSION
                value: ${ASSISTED_SERVICE_IMAGE}:${IMAGE_TAG}
              - name: CONTROLLER_IMAGE
                value: ${CONTROLLER_IMAGE}
              - name: AGENT_DOCKER_IMAGE
                value: ${AGENT_DOCKER_IMAGE}
              - name: CONNECTIVITY_CHECK_IMAGE
                value: ${CONNECTIVITY_CHECK_IMAGE}
              - name: INVENTORY_IMAGE
                value: ${INVENTORY_IMAGE}
              - name: FREE_ADDRESSES_IMAGE
                value: ${FREE_ADDRESSES_IMAGE}
              - name: DHCP_LEASE_ALLOCATOR_IMAGE
                value: ${DHCP_LEASE_ALLOCATOR_IMAGE}
            volumeMounts:
              - name: route53-creds
                mountPath: "/etc/.aws"
                readOnly: true
        volumes:
          - name: route53-creds
            secret:
              secretName: route53-creds
              optional: true
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: assisted-service
    name: assisted-service
  spec:
    ports:
      - name: assisted-svc
        port: 8090
        protocol: TCP
        targetPort: 8090
    selector:
      app: assisted-service
