---
parameters:
- name: IMAGE_SERVICE_IMAGE
  value: quay.io/app-sre/assisted-image-service
- name: IMAGE_TAG
  value: ''
  required: true
- name: OS_IMAGES
  value: '[{"openshift_version":"4.6","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img","version":"46.82.202012051820-0"},{"openshift_version":"4.7","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-4.7.13-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live-rootfs.x86_64.img","version":"47.83.202105220305-0"},{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img","version":"48.84.202107202156-0"},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-4.9.0-rc.4-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-live-rootfs.x86_64.img","version":"49.84.202109241334-0"},{"openshift_version":"4.9","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/arm64/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-4.9.0-rc.4-aarch64-live.aarch64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/arm64/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-4.9.0-rc.4-aarch64-live-rootfs.aarch64.img","version":"49.84.202109210947-0"}]' # os images
  required: false
- name: REPLICAS_COUNT
  value: "3"
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-image-service
  spec:
    selector:
      matchLabels:
        service: image-service
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          service: image-service
      spec:
        serviceAccountName: assisted-service
        containers:
          - name: assisted-image-service
            image: ${IMAGE_SERVICE_IMAGE}:${IMAGE_TAG}
            resources:
              requests:
                cpu: 100m
                memory: 400Mi
            ports:
              - protocol: TCP
                containerPort: 8080
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
            livenessProbe:
              httpGet:
                path: /live
                port: 8080
            env:
              - name: LISTEN_PORT
                value: "8080"
              - name: RHCOS_VERSIONS
                value: ${OS_IMAGES}
              - name: ASSISTED_SERVICE_SCHEME
                value: http
              - name: ASSISTED_SERVICE_HOST
                value: "assisted-service:8090"
              - name: REQUEST_AUTH_TYPE
                value: header
- apiVersion: v1
  kind: Service
  metadata:
    name: assisted-image-service
  spec:
    ports:
      - port: 8080
        protocol: TCP
    selector:
      service: image-service
