// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeregisterClusterNoContentCode is the HTTP code returned for type DeregisterClusterNoContent
const DeregisterClusterNoContentCode int = 204

/*DeregisterClusterNoContent Cluster deregistered

swagger:response deregisterClusterNoContent
*/
type DeregisterClusterNoContent struct {
}

// NewDeregisterClusterNoContent creates DeregisterClusterNoContent with default headers values
func NewDeregisterClusterNoContent() *DeregisterClusterNoContent {

	return &DeregisterClusterNoContent{}
}

// WriteResponse to the client
func (o *DeregisterClusterNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeregisterClusterNotFoundCode is the HTTP code returned for type DeregisterClusterNotFound
const DeregisterClusterNotFoundCode int = 404

/*DeregisterClusterNotFound Cluster not found

swagger:response deregisterClusterNotFound
*/
type DeregisterClusterNotFound struct {
}

// NewDeregisterClusterNotFound creates DeregisterClusterNotFound with default headers values
func NewDeregisterClusterNotFound() *DeregisterClusterNotFound {

	return &DeregisterClusterNotFound{}
}

// WriteResponse to the client
func (o *DeregisterClusterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
