// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// EnableNodeHandlerFunc turns a function with the right signature into a enable node handler
type EnableNodeHandlerFunc func(EnableNodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EnableNodeHandlerFunc) Handle(params EnableNodeParams) middleware.Responder {
	return fn(params)
}

// EnableNodeHandler interface for that can handle valid enable node params
type EnableNodeHandler interface {
	Handle(EnableNodeParams) middleware.Responder
}

// NewEnableNode creates a new http.Handler for the enable node operation
func NewEnableNode(ctx *middleware.Context, handler EnableNodeHandler) *EnableNode {
	return &EnableNode{Context: ctx, Handler: handler}
}

/*EnableNode swagger:route POST /nodes/{node_id}/actions/enable inventory enableNode

Enable a node for use

*/
type EnableNode struct {
	Context *middleware.Context
	Handler EnableNodeHandler
}

func (o *EnableNode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewEnableNodeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
