// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/openshift/assisted-service/models"
)

// DownloadInfraEnvDiscoveryImageHeadersOKCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersOK
const DownloadInfraEnvDiscoveryImageHeadersOKCode int = 200

/*DownloadInfraEnvDiscoveryImageHeadersOK Success.

swagger:response downloadInfraEnvDiscoveryImageHeadersOK
*/
type DownloadInfraEnvDiscoveryImageHeadersOK struct {
	/*Size of the ISO in bytes

	 */
	ContentLength int64 `json:"Content-Length"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersOK creates DownloadInfraEnvDiscoveryImageHeadersOK with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersOK() *DownloadInfraEnvDiscoveryImageHeadersOK {

	return &DownloadInfraEnvDiscoveryImageHeadersOK{}
}

// WithContentLength adds the contentLength to the download infra env discovery image headers o k response
func (o *DownloadInfraEnvDiscoveryImageHeadersOK) WithContentLength(contentLength int64) *DownloadInfraEnvDiscoveryImageHeadersOK {
	o.ContentLength = contentLength
	return o
}

// SetContentLength sets the contentLength to the download infra env discovery image headers o k response
func (o *DownloadInfraEnvDiscoveryImageHeadersOK) SetContentLength(contentLength int64) {
	o.ContentLength = contentLength
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Content-Length

	contentLength := swag.FormatInt64(o.ContentLength)
	if contentLength != "" {
		rw.Header().Set("Content-Length", contentLength)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DownloadInfraEnvDiscoveryImageHeadersBadRequestCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersBadRequest
const DownloadInfraEnvDiscoveryImageHeadersBadRequestCode int = 400

/*DownloadInfraEnvDiscoveryImageHeadersBadRequest Error.

swagger:response downloadInfraEnvDiscoveryImageHeadersBadRequest
*/
type DownloadInfraEnvDiscoveryImageHeadersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersBadRequest creates DownloadInfraEnvDiscoveryImageHeadersBadRequest with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersBadRequest() *DownloadInfraEnvDiscoveryImageHeadersBadRequest {

	return &DownloadInfraEnvDiscoveryImageHeadersBadRequest{}
}

// WithPayload adds the payload to the download infra env discovery image headers bad request response
func (o *DownloadInfraEnvDiscoveryImageHeadersBadRequest) WithPayload(payload *models.Error) *DownloadInfraEnvDiscoveryImageHeadersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers bad request response
func (o *DownloadInfraEnvDiscoveryImageHeadersBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersUnauthorizedCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersUnauthorized
const DownloadInfraEnvDiscoveryImageHeadersUnauthorizedCode int = 401

/*DownloadInfraEnvDiscoveryImageHeadersUnauthorized Unauthorized.

swagger:response downloadInfraEnvDiscoveryImageHeadersUnauthorized
*/
type DownloadInfraEnvDiscoveryImageHeadersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersUnauthorized creates DownloadInfraEnvDiscoveryImageHeadersUnauthorized with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersUnauthorized() *DownloadInfraEnvDiscoveryImageHeadersUnauthorized {

	return &DownloadInfraEnvDiscoveryImageHeadersUnauthorized{}
}

// WithPayload adds the payload to the download infra env discovery image headers unauthorized response
func (o *DownloadInfraEnvDiscoveryImageHeadersUnauthorized) WithPayload(payload *models.InfraError) *DownloadInfraEnvDiscoveryImageHeadersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers unauthorized response
func (o *DownloadInfraEnvDiscoveryImageHeadersUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersForbiddenCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersForbidden
const DownloadInfraEnvDiscoveryImageHeadersForbiddenCode int = 403

/*DownloadInfraEnvDiscoveryImageHeadersForbidden Forbidden.

swagger:response downloadInfraEnvDiscoveryImageHeadersForbidden
*/
type DownloadInfraEnvDiscoveryImageHeadersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersForbidden creates DownloadInfraEnvDiscoveryImageHeadersForbidden with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersForbidden() *DownloadInfraEnvDiscoveryImageHeadersForbidden {

	return &DownloadInfraEnvDiscoveryImageHeadersForbidden{}
}

// WithPayload adds the payload to the download infra env discovery image headers forbidden response
func (o *DownloadInfraEnvDiscoveryImageHeadersForbidden) WithPayload(payload *models.InfraError) *DownloadInfraEnvDiscoveryImageHeadersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers forbidden response
func (o *DownloadInfraEnvDiscoveryImageHeadersForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersNotFoundCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersNotFound
const DownloadInfraEnvDiscoveryImageHeadersNotFoundCode int = 404

/*DownloadInfraEnvDiscoveryImageHeadersNotFound Error.

swagger:response downloadInfraEnvDiscoveryImageHeadersNotFound
*/
type DownloadInfraEnvDiscoveryImageHeadersNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersNotFound creates DownloadInfraEnvDiscoveryImageHeadersNotFound with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersNotFound() *DownloadInfraEnvDiscoveryImageHeadersNotFound {

	return &DownloadInfraEnvDiscoveryImageHeadersNotFound{}
}

// WithPayload adds the payload to the download infra env discovery image headers not found response
func (o *DownloadInfraEnvDiscoveryImageHeadersNotFound) WithPayload(payload *models.Error) *DownloadInfraEnvDiscoveryImageHeadersNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers not found response
func (o *DownloadInfraEnvDiscoveryImageHeadersNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowedCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed
const DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowedCode int = 405

/*DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed Method Not Allowed.

swagger:response downloadInfraEnvDiscoveryImageHeadersMethodNotAllowed
*/
type DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed struct {
}

// NewDownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed creates DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed() *DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed {

	return &DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DownloadInfraEnvDiscoveryImageHeadersConflictCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersConflict
const DownloadInfraEnvDiscoveryImageHeadersConflictCode int = 409

/*DownloadInfraEnvDiscoveryImageHeadersConflict Error.

swagger:response downloadInfraEnvDiscoveryImageHeadersConflict
*/
type DownloadInfraEnvDiscoveryImageHeadersConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersConflict creates DownloadInfraEnvDiscoveryImageHeadersConflict with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersConflict() *DownloadInfraEnvDiscoveryImageHeadersConflict {

	return &DownloadInfraEnvDiscoveryImageHeadersConflict{}
}

// WithPayload adds the payload to the download infra env discovery image headers conflict response
func (o *DownloadInfraEnvDiscoveryImageHeadersConflict) WithPayload(payload *models.Error) *DownloadInfraEnvDiscoveryImageHeadersConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers conflict response
func (o *DownloadInfraEnvDiscoveryImageHeadersConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersInternalServerErrorCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersInternalServerError
const DownloadInfraEnvDiscoveryImageHeadersInternalServerErrorCode int = 500

/*DownloadInfraEnvDiscoveryImageHeadersInternalServerError Error.

swagger:response downloadInfraEnvDiscoveryImageHeadersInternalServerError
*/
type DownloadInfraEnvDiscoveryImageHeadersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersInternalServerError creates DownloadInfraEnvDiscoveryImageHeadersInternalServerError with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersInternalServerError() *DownloadInfraEnvDiscoveryImageHeadersInternalServerError {

	return &DownloadInfraEnvDiscoveryImageHeadersInternalServerError{}
}

// WithPayload adds the payload to the download infra env discovery image headers internal server error response
func (o *DownloadInfraEnvDiscoveryImageHeadersInternalServerError) WithPayload(payload *models.Error) *DownloadInfraEnvDiscoveryImageHeadersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers internal server error response
func (o *DownloadInfraEnvDiscoveryImageHeadersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadInfraEnvDiscoveryImageHeadersNotImplementedCode is the HTTP code returned for type DownloadInfraEnvDiscoveryImageHeadersNotImplemented
const DownloadInfraEnvDiscoveryImageHeadersNotImplementedCode int = 501

/*DownloadInfraEnvDiscoveryImageHeadersNotImplemented Not implemented.

swagger:response downloadInfraEnvDiscoveryImageHeadersNotImplemented
*/
type DownloadInfraEnvDiscoveryImageHeadersNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDownloadInfraEnvDiscoveryImageHeadersNotImplemented creates DownloadInfraEnvDiscoveryImageHeadersNotImplemented with default headers values
func NewDownloadInfraEnvDiscoveryImageHeadersNotImplemented() *DownloadInfraEnvDiscoveryImageHeadersNotImplemented {

	return &DownloadInfraEnvDiscoveryImageHeadersNotImplemented{}
}

// WithPayload adds the payload to the download infra env discovery image headers not implemented response
func (o *DownloadInfraEnvDiscoveryImageHeadersNotImplemented) WithPayload(payload *models.Error) *DownloadInfraEnvDiscoveryImageHeadersNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download infra env discovery image headers not implemented response
func (o *DownloadInfraEnvDiscoveryImageHeadersNotImplemented) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadInfraEnvDiscoveryImageHeadersNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
