// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DownloadClusterISOCloneHandlerFunc turns a function with the right signature into a download cluster i s o clone handler
type DownloadClusterISOCloneHandlerFunc func(DownloadClusterISOCloneParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadClusterISOCloneHandlerFunc) Handle(params DownloadClusterISOCloneParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DownloadClusterISOCloneHandler interface for that can handle valid download cluster i s o clone params
type DownloadClusterISOCloneHandler interface {
	Handle(DownloadClusterISOCloneParams, interface{}) middleware.Responder
}

// NewDownloadClusterISOClone creates a new http.Handler for the download cluster i s o clone operation
func NewDownloadClusterISOClone(ctx *middleware.Context, handler DownloadClusterISOCloneHandler) *DownloadClusterISOClone {
	return &DownloadClusterISOClone{Context: ctx, Handler: handler}
}

/*DownloadClusterISOClone swagger:route GET /clusters/{cluster_id}/downloads/image.iso installer downloadClusterISOClone

Downloads the OpenShift per-cluster Discovery ISO. Provided for compatability with Dell IDRAC.

*/
type DownloadClusterISOClone struct {
	Context *middleware.Context
	Handler DownloadClusterISOCloneHandler
}

func (o *DownloadClusterISOClone) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadClusterISOCloneParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
