// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/filanov/bm-inventory/models"
)

// GetNextStepsOKCode is the HTTP code returned for type GetNextStepsOK
const GetNextStepsOKCode int = 200

/*GetNextStepsOK Success.

swagger:response getNextStepsOK
*/
type GetNextStepsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Steps `json:"body,omitempty"`
}

// NewGetNextStepsOK creates GetNextStepsOK with default headers values
func NewGetNextStepsOK() *GetNextStepsOK {

	return &GetNextStepsOK{}
}

// WithPayload adds the payload to the get next steps o k response
func (o *GetNextStepsOK) WithPayload(payload *models.Steps) *GetNextStepsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next steps o k response
func (o *GetNextStepsOK) SetPayload(payload *models.Steps) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextStepsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNextStepsNotFoundCode is the HTTP code returned for type GetNextStepsNotFound
const GetNextStepsNotFoundCode int = 404

/*GetNextStepsNotFound Error.

swagger:response getNextStepsNotFound
*/
type GetNextStepsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNextStepsNotFound creates GetNextStepsNotFound with default headers values
func NewGetNextStepsNotFound() *GetNextStepsNotFound {

	return &GetNextStepsNotFound{}
}

// WithPayload adds the payload to the get next steps not found response
func (o *GetNextStepsNotFound) WithPayload(payload *models.Error) *GetNextStepsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next steps not found response
func (o *GetNextStepsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextStepsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNextStepsInternalServerErrorCode is the HTTP code returned for type GetNextStepsInternalServerError
const GetNextStepsInternalServerErrorCode int = 500

/*GetNextStepsInternalServerError Error.

swagger:response getNextStepsInternalServerError
*/
type GetNextStepsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNextStepsInternalServerError creates GetNextStepsInternalServerError with default headers values
func NewGetNextStepsInternalServerError() *GetNextStepsInternalServerError {

	return &GetNextStepsInternalServerError{}
}

// WithPayload adds the payload to the get next steps internal server error response
func (o *GetNextStepsInternalServerError) WithPayload(payload *models.Error) *GetNextStepsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next steps internal server error response
func (o *GetNextStepsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextStepsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
