// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/filanov/bm-inventory/models"
)

// ListClustersOKCode is the HTTP code returned for type ListClustersOK
const ListClustersOKCode int = 200

/*ListClustersOK Success.

swagger:response listClustersOK
*/
type ListClustersOK struct {

	/*
	  In: Body
	*/
	Payload models.ClusterList `json:"body,omitempty"`
}

// NewListClustersOK creates ListClustersOK with default headers values
func NewListClustersOK() *ListClustersOK {

	return &ListClustersOK{}
}

// WithPayload adds the payload to the list clusters o k response
func (o *ListClustersOK) WithPayload(payload models.ClusterList) *ListClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters o k response
func (o *ListClustersOK) SetPayload(payload models.ClusterList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ClusterList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListClustersInternalServerErrorCode is the HTTP code returned for type ListClustersInternalServerError
const ListClustersInternalServerErrorCode int = 500

/*ListClustersInternalServerError Error.

swagger:response listClustersInternalServerError
*/
type ListClustersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListClustersInternalServerError creates ListClustersInternalServerError with default headers values
func NewListClustersInternalServerError() *ListClustersInternalServerError {

	return &ListClustersInternalServerError{}
}

// WithPayload adds the payload to the list clusters internal server error response
func (o *ListClustersInternalServerError) WithPayload(payload *models.Error) *ListClustersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters internal server error response
func (o *ListClustersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
