// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegenerateInfraEnvSigningKeyHandlerFunc turns a function with the right signature into a regenerate infra env signing key handler
type RegenerateInfraEnvSigningKeyHandlerFunc func(RegenerateInfraEnvSigningKeyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RegenerateInfraEnvSigningKeyHandlerFunc) Handle(params RegenerateInfraEnvSigningKeyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RegenerateInfraEnvSigningKeyHandler interface for that can handle valid regenerate infra env signing key params
type RegenerateInfraEnvSigningKeyHandler interface {
	Handle(RegenerateInfraEnvSigningKeyParams, interface{}) middleware.Responder
}

// NewRegenerateInfraEnvSigningKey creates a new http.Handler for the regenerate infra env signing key operation
func NewRegenerateInfraEnvSigningKey(ctx *middleware.Context, handler RegenerateInfraEnvSigningKeyHandler) *RegenerateInfraEnvSigningKey {
	return &RegenerateInfraEnvSigningKey{Context: ctx, Handler: handler}
}

/*
	RegenerateInfraEnvSigningKey swagger:route POST /v2/infra-envs/{infra_env_id}/regenerate-signing-key installer regenerateInfraEnvSigningKey

Regenerate InfraEnv token signing key.
*/
type RegenerateInfraEnvSigningKey struct {
	Context *middleware.Context
	Handler RegenerateInfraEnvSigningKeyHandler
}

func (o *RegenerateInfraEnvSigningKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRegenerateInfraEnvSigningKeyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
