// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// UpdateHostInstallProgressOKCode is the HTTP code returned for type UpdateHostInstallProgressOK
const UpdateHostInstallProgressOKCode int = 200

/*UpdateHostInstallProgressOK Update install progress

swagger:response updateHostInstallProgressOK
*/
type UpdateHostInstallProgressOK struct {
}

// NewUpdateHostInstallProgressOK creates UpdateHostInstallProgressOK with default headers values
func NewUpdateHostInstallProgressOK() *UpdateHostInstallProgressOK {

	return &UpdateHostInstallProgressOK{}
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateHostInstallProgressUnauthorizedCode is the HTTP code returned for type UpdateHostInstallProgressUnauthorized
const UpdateHostInstallProgressUnauthorizedCode int = 401

/*UpdateHostInstallProgressUnauthorized Unauthorized.

swagger:response updateHostInstallProgressUnauthorized
*/
type UpdateHostInstallProgressUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewUpdateHostInstallProgressUnauthorized creates UpdateHostInstallProgressUnauthorized with default headers values
func NewUpdateHostInstallProgressUnauthorized() *UpdateHostInstallProgressUnauthorized {

	return &UpdateHostInstallProgressUnauthorized{}
}

// WithPayload adds the payload to the update host install progress unauthorized response
func (o *UpdateHostInstallProgressUnauthorized) WithPayload(payload *models.InfraError) *UpdateHostInstallProgressUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host install progress unauthorized response
func (o *UpdateHostInstallProgressUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHostInstallProgressForbiddenCode is the HTTP code returned for type UpdateHostInstallProgressForbidden
const UpdateHostInstallProgressForbiddenCode int = 403

/*UpdateHostInstallProgressForbidden Forbidden.

swagger:response updateHostInstallProgressForbidden
*/
type UpdateHostInstallProgressForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewUpdateHostInstallProgressForbidden creates UpdateHostInstallProgressForbidden with default headers values
func NewUpdateHostInstallProgressForbidden() *UpdateHostInstallProgressForbidden {

	return &UpdateHostInstallProgressForbidden{}
}

// WithPayload adds the payload to the update host install progress forbidden response
func (o *UpdateHostInstallProgressForbidden) WithPayload(payload *models.InfraError) *UpdateHostInstallProgressForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host install progress forbidden response
func (o *UpdateHostInstallProgressForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHostInstallProgressNotFoundCode is the HTTP code returned for type UpdateHostInstallProgressNotFound
const UpdateHostInstallProgressNotFoundCode int = 404

/*UpdateHostInstallProgressNotFound Error.

swagger:response updateHostInstallProgressNotFound
*/
type UpdateHostInstallProgressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHostInstallProgressNotFound creates UpdateHostInstallProgressNotFound with default headers values
func NewUpdateHostInstallProgressNotFound() *UpdateHostInstallProgressNotFound {

	return &UpdateHostInstallProgressNotFound{}
}

// WithPayload adds the payload to the update host install progress not found response
func (o *UpdateHostInstallProgressNotFound) WithPayload(payload *models.Error) *UpdateHostInstallProgressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host install progress not found response
func (o *UpdateHostInstallProgressNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHostInstallProgressMethodNotAllowedCode is the HTTP code returned for type UpdateHostInstallProgressMethodNotAllowed
const UpdateHostInstallProgressMethodNotAllowedCode int = 405

/*UpdateHostInstallProgressMethodNotAllowed Method Not Allowed.

swagger:response updateHostInstallProgressMethodNotAllowed
*/
type UpdateHostInstallProgressMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHostInstallProgressMethodNotAllowed creates UpdateHostInstallProgressMethodNotAllowed with default headers values
func NewUpdateHostInstallProgressMethodNotAllowed() *UpdateHostInstallProgressMethodNotAllowed {

	return &UpdateHostInstallProgressMethodNotAllowed{}
}

// WithPayload adds the payload to the update host install progress method not allowed response
func (o *UpdateHostInstallProgressMethodNotAllowed) WithPayload(payload *models.Error) *UpdateHostInstallProgressMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host install progress method not allowed response
func (o *UpdateHostInstallProgressMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHostInstallProgressInternalServerErrorCode is the HTTP code returned for type UpdateHostInstallProgressInternalServerError
const UpdateHostInstallProgressInternalServerErrorCode int = 500

/*UpdateHostInstallProgressInternalServerError Error.

swagger:response updateHostInstallProgressInternalServerError
*/
type UpdateHostInstallProgressInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHostInstallProgressInternalServerError creates UpdateHostInstallProgressInternalServerError with default headers values
func NewUpdateHostInstallProgressInternalServerError() *UpdateHostInstallProgressInternalServerError {

	return &UpdateHostInstallProgressInternalServerError{}
}

// WithPayload adds the payload to the update host install progress internal server error response
func (o *UpdateHostInstallProgressInternalServerError) WithPayload(payload *models.Error) *UpdateHostInstallProgressInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host install progress internal server error response
func (o *UpdateHostInstallProgressInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostInstallProgressInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
