// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V2DownloadClusterLogsHandlerFunc turns a function with the right signature into a v2 download cluster logs handler
type V2DownloadClusterLogsHandlerFunc func(V2DownloadClusterLogsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn V2DownloadClusterLogsHandlerFunc) Handle(params V2DownloadClusterLogsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// V2DownloadClusterLogsHandler interface for that can handle valid v2 download cluster logs params
type V2DownloadClusterLogsHandler interface {
	Handle(V2DownloadClusterLogsParams, interface{}) middleware.Responder
}

// NewV2DownloadClusterLogs creates a new http.Handler for the v2 download cluster logs operation
func NewV2DownloadClusterLogs(ctx *middleware.Context, handler V2DownloadClusterLogsHandler) *V2DownloadClusterLogs {
	return &V2DownloadClusterLogs{Context: ctx, Handler: handler}
}

/*
	V2DownloadClusterLogs swagger:route GET /v2/clusters/{cluster_id}/logs installer v2DownloadClusterLogs

Download cluster logs.
*/
type V2DownloadClusterLogs struct {
	Context *middleware.Context
	Handler V2DownloadClusterLogsHandler
}

func (o *V2DownloadClusterLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewV2DownloadClusterLogsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
