// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V2DownloadClusterCredentialsHandlerFunc turns a function with the right signature into a v2 download cluster credentials handler
type V2DownloadClusterCredentialsHandlerFunc func(V2DownloadClusterCredentialsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn V2DownloadClusterCredentialsHandlerFunc) Handle(params V2DownloadClusterCredentialsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// V2DownloadClusterCredentialsHandler interface for that can handle valid v2 download cluster credentials params
type V2DownloadClusterCredentialsHandler interface {
	Handle(V2DownloadClusterCredentialsParams, interface{}) middleware.Responder
}

// NewV2DownloadClusterCredentials creates a new http.Handler for the v2 download cluster credentials operation
func NewV2DownloadClusterCredentials(ctx *middleware.Context, handler V2DownloadClusterCredentialsHandler) *V2DownloadClusterCredentials {
	return &V2DownloadClusterCredentials{Context: ctx, Handler: handler}
}

/*
	V2DownloadClusterCredentials swagger:route GET /v2/clusters/{cluster_id}/downloads/credentials installer v2DownloadClusterCredentials

Downloads credentials relating to the installed/installing cluster.
*/
type V2DownloadClusterCredentials struct {
	Context *middleware.Context
	Handler V2DownloadClusterCredentialsHandler
}

func (o *V2DownloadClusterCredentials) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewV2DownloadClusterCredentialsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
