// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V2UpdateHostInstallProgressHandlerFunc turns a function with the right signature into a v2 update host install progress handler
type V2UpdateHostInstallProgressHandlerFunc func(V2UpdateHostInstallProgressParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn V2UpdateHostInstallProgressHandlerFunc) Handle(params V2UpdateHostInstallProgressParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// V2UpdateHostInstallProgressHandler interface for that can handle valid v2 update host install progress params
type V2UpdateHostInstallProgressHandler interface {
	Handle(V2UpdateHostInstallProgressParams, interface{}) middleware.Responder
}

// NewV2UpdateHostInstallProgress creates a new http.Handler for the v2 update host install progress operation
func NewV2UpdateHostInstallProgress(ctx *middleware.Context, handler V2UpdateHostInstallProgressHandler) *V2UpdateHostInstallProgress {
	return &V2UpdateHostInstallProgress{Context: ctx, Handler: handler}
}

/*
	V2UpdateHostInstallProgress swagger:route PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/progress installer v2UpdateHostInstallProgress

Update installation progress.
*/
type V2UpdateHostInstallProgress struct {
	Context *middleware.Context
	Handler V2UpdateHostInstallProgressHandler
}

func (o *V2UpdateHostInstallProgress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewV2UpdateHostInstallProgressParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
