// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInfraEnvParams creates a new GetInfraEnvParams object
// with the default values initialized.
func NewGetInfraEnvParams() *GetInfraEnvParams {
	var ()
	return &GetInfraEnvParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInfraEnvParamsWithTimeout creates a new GetInfraEnvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInfraEnvParamsWithTimeout(timeout time.Duration) *GetInfraEnvParams {
	var ()
	return &GetInfraEnvParams{

		timeout: timeout,
	}
}

// NewGetInfraEnvParamsWithContext creates a new GetInfraEnvParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInfraEnvParamsWithContext(ctx context.Context) *GetInfraEnvParams {
	var ()
	return &GetInfraEnvParams{

		Context: ctx,
	}
}

// NewGetInfraEnvParamsWithHTTPClient creates a new GetInfraEnvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInfraEnvParamsWithHTTPClient(client *http.Client) *GetInfraEnvParams {
	var ()
	return &GetInfraEnvParams{
		HTTPClient: client,
	}
}

/*GetInfraEnvParams contains all the parameters to send to the API endpoint
for the get infra env operation typically these are written to a http.Request
*/
type GetInfraEnvParams struct {

	/*InfraEnvID
	  The InfraEnv to be retrieved.

	*/
	InfraEnvID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get infra env params
func (o *GetInfraEnvParams) WithTimeout(timeout time.Duration) *GetInfraEnvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get infra env params
func (o *GetInfraEnvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get infra env params
func (o *GetInfraEnvParams) WithContext(ctx context.Context) *GetInfraEnvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get infra env params
func (o *GetInfraEnvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get infra env params
func (o *GetInfraEnvParams) WithHTTPClient(client *http.Client) *GetInfraEnvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get infra env params
func (o *GetInfraEnvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInfraEnvID adds the infraEnvID to the get infra env params
func (o *GetInfraEnvParams) WithInfraEnvID(infraEnvID strfmt.UUID) *GetInfraEnvParams {
	o.SetInfraEnvID(infraEnvID)
	return o
}

// SetInfraEnvID adds the infraEnvId to the get infra env params
func (o *GetInfraEnvParams) SetInfraEnvID(infraEnvID strfmt.UUID) {
	o.InfraEnvID = infraEnvID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInfraEnvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param infra_env_id
	if err := r.SetPathParam("infra_env_id", o.InfraEnvID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
