name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        sudo pip install strato-skipper
        mkdir -p ~/.docker
        echo "{}" > ~/.docker/config.json
        touch ${HOME}/.gitconfig
        ln -s Dockerfile.assisted-service Dockerfile
    - name: build
      run: |
        skipper make build
    - name: create python client
      run: |
        skipper make create-python-client
    - name: Get release version
      id: get_version
      run: echo ::set-env name=GIT_REVISION::$(echo ${GITHUB_SHA})
    - name: Get tag
      id: get_tag
      run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
    - name: Publish assisted-service to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: assisted-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY: 'quay.io/ocpmetal'
        dockerfile: "Dockerfile.assisted-service"
        buildargs: GIT_REVISION
        tags: "${{ env.GIT_TAG }},${{ env.GIT_REVISION }}"
