// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Base base
// swagger:model base
type Base struct {

	// href
	Href string `json:"href,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`
}

// Validate validates this base
func (m *Base) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Base) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Base) UnmarshalBinary(b []byte) error {
	var res Base
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
