// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// L3Connectivity l3 connectivity
//
// swagger:model l3-connectivity
type L3Connectivity struct {

	// outgoing nic
	OutgoingNic string `json:"outgoing-nic,omitempty"`

	// remote ip address
	RemoteIPAddress string `json:"remote-ip-address,omitempty"`

	// successful
	Successful bool `json:"successful,omitempty"`
}

// Validate validates this l3 connectivity
func (m *L3Connectivity) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *L3Connectivity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L3Connectivity) UnmarshalBinary(b []byte) error {
	var res L3Connectivity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
